# BrokerFlow AI - docker-compose.yml

version: '3.8'

services:
  # API Service
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./inbox:/app/inbox
      - ./output:/app/output
      - ./templates:/app/templates
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn api_b2b:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Dashboard Service
  frontend:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_BASE_URL=http://api:8000/api/v1
    volumes:
      - ./inbox:/app/inbox
      - ./output:/app/output
      - ./templates:/app/templates
      - ./logs:/app/logs
      - ./streamlit_config.toml:/root/.streamlit/config.toml
    depends_on:
      - db
      - api
    restart: unless-stopped
    command: streamlit run frontend/dashboard.py --server.port 8501

  # Document Processing Service
  processor:
    build: .
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./inbox:/app/inbox
      - ./output:/app/output
      - ./templates:/app/templates
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    command: python main.py

  # Database
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

  # Database management tool
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

  # Redis cache (for future use)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  db_data: