version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
      - hf_cache:/root/.cache/huggingface
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  hf_cache: